IndexError: string index out of range
Traceback (most recent call last):
  File "thrower.py", line 127, in <module>
    bot.act(sys.argv[1])
  File "thrower.py", line 116, in act
    self.read_board()
  File "thrower.py", line 73, in read_board
    self.neighbors[d] = board[y-dy][x+dx]
IndexError: string index out of range
Traceback (most recent call last):
  File "thrower.py", line 127, in <module>
    bot.act(sys.argv[1])
  File "thrower.py", line 114, in act
    self.load()
  File "thrower.py", line 43, in load
    history = json.load(f)
  File "/Users/gray/anaconda/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Users/gray/anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/gray/anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/gray/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
KeyboardInterrupt
Traceback (most recent call last):
  File "thrower.py", line 127, in <module>
    bot.act(sys.argv[1])
  File "thrower.py", line 122, in act
    self.save()
  File "thrower.py", line 56, in save
    json.dump(history, f)
  File "/Users/gray/anaconda/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/Users/gray/anaconda/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/Users/gray/anaconda/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/Users/gray/anaconda/lib/python2.7/json/encoder.py", line 398, in _iterencode_dict
    yield str(value)
KeyboardInterrupt
